import { Intent } from './intent.types';

export const INTENT_KEYWORDS: Record<
  Intent,
  string[]
> = {
  NORMAL_CHAT: [
    'hi',
    'hello',
    'hey',
    'hii',
    'helo',
    'how are you',
    'how r you',
    'good morning',
    'good afternoon',
    'good evening',
    'good night',
    'thanks',
    'thank you',
    'okay',
    'ok',
    'bye',
    'goodbye',
  ],

  PROJECT_START: [
    'need a website',
    'want a website',
    'website needed',
    'website required',
    'build a website',
    'create a website',
    'make a website',
    'website kavali',
    'website cheyali',
    'website build cheyali',
    'app kavali',
    'application kavali',
    'web app kavali',
    'ecommerce website',
    'e-commerce website',
    'online store',
    'saas website',
    'saas product',
  ],

  PROJECT_DISCOVERY: [
    'business',
    'business goal',
    'target audience',
    'customers',
    'industry',
    'business type',
    'project type',
    'website type',
    'mee business',
    'mee goal',
    'mee industry',
    'target customers',
  ],

  FEATURES: [
    'features',
    'feature',
    'functionality',
    'online ordering',
    'online order',
    'ordering',
    'order online',
    'food ordering',
    'booking',
    'booking system',
    'appointment',
    'reservation',
    'login',
    'authentication',
    'payment',
    'payment gateway',
    'checkout',
    'cart',
    'dashboard',
    'admin dashboard',
    'admin panel',
    'notification',
    'contact form',
    'search',
    'search bar',
    'filter',
    'wishlist',
    'reviews',
    'testimonials',
    'live chat',
    'chat',
    'cms',
  ],

  TECHNOLOGY: [
    'technology',
    'technology stack',
    'tech stack',
    'tech',
    'react',
    'nextjs',
    'next.js',
    'tailwind',
    'tailwind css',
    'nestjs',
    'nest.js',
    'node.js',
    'nodejs',
    'typescript',
    'javascript',
    'python',
    'django',
    'fastapi',
    'postgresql',
    'postgres',
    'mysql',
    'mongodb',
    'mongo',
    'frontend',
    'backend',
  ],

  SEO: [
    'seo',
    'seo optimization',
    'search engine optimization',
    'google ranking',
    'search ranking',
    'search engine',
    'google search',
    'rank on google',
    'google lo',
  ],

  PRICING: [
    'price',
    'pricing',
    'cost',
    'how much',
    'how much does',
    'website cost',
    'website price',
    'pricing details',
    'price details',
    'entha cost',
    'entha price',
    'entha',
  ],

  TIMELINE: [
    'timeline',
    'how long',
    'how many days',
    'days',
    'when',
    'completion time',
    'delivery time',
    'eppudu',
    'entha time',
    'entha days',
    'when complete',
  ],

  PROPOSAL: [
    'proposal',
    'quote',
    'quotation',
    'project plan',
    'summary',
    'send proposal',
    'proposal send',
  ],

  GENERAL_QUESTION: [
    'what is',
    'what are',
    'how does',
    'how do',
    'why',
    'explain',
    'meaning',
    'ante enti',
    'what do you mean',
  ],
};